spring:
  application:
    name: noru

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  korea-invest:
    base-url: https://openapi.koreainvestment.com:9443
    appkey: ${APP_KEY}
    appsecret: ${APP_SECRET}